- name: force docker handlers
  meta: flush_handlers

- name: Check docker info
  shell: docker info
  changed_when: False
  register: docker_info

- name: Include "{{swarn_type_of_node}}" recipe
  include: "{{swarn_type_of_node}}.yml"

