- name: Wait for docker in manager to start
  wait_for:
    host: "{{ swarn_manager_address }}"
    port: "{{ swarn_manager_port }}"
    timeout: 120

- name: Get the worker join-token.
  shell: docker swarm join-token -q worker
  changed_when: False
  register: docker_worker_token
  delegate_to: "{{ swarn_manager_address }}"

- name: Join the pending Swarm worker nodes.
  shell: docker swarm join --token "{{ docker_worker_token.stdout }}" {{ swarn_manager_address }}:{{ swarn_manager_port }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1 and docker_info.stdout.find('Swarm: pending') == -1"

