# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    build: db
    depends_on:
      - db

  #api:
  #  build: api
  #  image: rhedgomez/hygieia-api
  #  depends_on:
  #    - db-setup
  #  ports:
  #    - "8080:8080"

  #api-audit:
  # build: api-audit
  # image: rhedgomez/hygieia-apiaudit
  # depends_on:
  #    - db-setup
  #  ports:
  #   - "8081:8080"

  ui:
    build: UI
    image: rhedgomez/hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"

  #appdynamics-collector:
  # build: collectors/performance/appdynamics
  #  image: rhedgomez/hygieia-appdynamics-collector
  #  depends_on:
  #    - db-setup

  #artifactory-artifact-collector:
  #  build: collectors/artifact/artifactory
  #  image: rhedgomez/hygieia-artifactory-artifact-collector
  #  depends_on:
  #    - db-setup

# bamboo-build-collector:
#    build: collectors/build/bamboo
#    image: rhedgomez/hygieia-bamboo-build-collector
#    depends_on:
#      - db-setup

#  bitbucket-collector:
#    build: collectors/scm/bitbucket
#    image: rhedgomez/hygieia-bitbucket-scm-collector
#    depends_on:
#      - db-setup

#  chat-ops-collector:
#    build: collectors/misc/chat-ops
#    image: rhedgomez/hygieia-chat-ops-collector
#    depends_on:
#      - db-setup

#  hpsm-cmdb-collector:
#    build: collectors/cmdb/hpsm
#    image: rhedgomez/hygieia-hspm-cmdb-collector
#    depends_on:
#      - db-setup

#  github-collector:
#    build: collectors/scm/github
#    image: rhedgomez/hygieia-github-scm-collector
#    depends_on:
#      - db-setup

  #github-graphql-collector:
   # build: collectors/scm/github-graphql
    #image: hygieia-github-graphql-scm-collector
    #depends_on:
     # - db-setup

#  gitlab-feature-collector:
#    build: collectors/feature/gitlab
#    image: rhedgomez/hygieia-gitlab-feature-collector
#    depends_on:
#      - db-setup

#  gitlab-scm-collector:
#    build: collectors/feature/gitlab
#    image: rhedgomez/hygieia-gitlab-scm-collector
#    depends_on:
#      - db-setup

#  jenkins-build-collector:
#    build: collectors/build/jenkins
#    image: rhedgomez/hygieia-jenkins-build-collector
#    depends_on:
#      - db-setup

#  jenkins-codequality-collector:
#    build: collectors/build/jenkins-codequality
#    image: rhedgomez/hygieia-jenkins-codequality-collector
#    depends_on:
#      - db-setup

#  jenkins-cucumber-test-collector:
#    build: collectors/build/jenkins-cucumber
#    image: rhedgomez/hygieia-jenkins-cucumber-test-collector
#    depends_on:
#      - db-setup

#  jira-collector:
#    build: collectors/feature/jira
#    image: rhedgomez/hygieia-jira-feature-collector
#    depends_on:
#      - db-setup

#  nexus-iq-collector:
#    build: collectors/library-policy/nexus-iq-collector
#    image: rhedgomez/hygieia-nexus-iq-collector
#    depends_on:
#      - db-setup

#  sonar-codequality-collector:
#    build: collectors/build/sonar
#    image: rhedgomez/hygieia-sonar-codequality-collector
#    depends_on:
#      - db-setup

#  subversion-collector:
#    build: collectors/scm/subversion
#    image: rhedgomez/hygieia-subversion-scm-collector
#    depends_on:
#      - db-setup

#  udeploy-collector:
#    build: collectors/deploy/udeploy
#    image: rhedgomez/hygieia-udeploy-collector
#    depends_on:
#      - db-setup

#  versionone-collector:
#    build: collectors/feature/versionone
#    image: rhedgomez/hygieia-versionone
#    depends_on:
#      - db-setup

#  xldeploy-collector:
#    build: collectors/deploy/xldeploy
#    image: rhedgomez/hygieia-xldeploy-collector
#    depends_on:
#      - db-setup

#  score-collector:
#    build: collectors/misc/score
#    image: rhedgomez/hygieia-score-collector
#    depends_on:
#      - db-setup

volumes:
  db-data: