#Upload custom sshkey pair to AWS

- hosts:  localhost

  tasks:
    - name: Uploading my public Key
      ec2_key:
        name: RhedsAWSPublickey
        region: us-east-1
        key_material: '<paste content of your id_rsa.pub>'
        state: present
